// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfggbudugrgyzohonnld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZ2didWR1Z3JneXpvaG9ubmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTc0MzksImV4cCI6MjA2NTkzMzQzOX0.NFxN9F7_KSlLSw_Wr45TEhZT5ASdy0DIu49DoE3fQFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);